spring:
  tomcat:
    basedir: ./tomcat
    access-log-enabled: true
    accesslog:
      directory: ./access-log

#########################
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.eugene.sumarry.permission.model
  type-handlers-package: com.eugene.sumarry.permission.typeHandler
  configuration:
    cache-enabled: true
    # mybatis内部使用logImpl的对象来接收日志的实现类, 若配置了此内容
    # mybatis则会采用自带的方式生成日志, 配置了logback后，则会采用logback
    # 生成日志，因为logback也是logImpl类型的实现类
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
